version: '3'
services:
  api:
    build: .

  db:
    image: postgres:12.4-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./db:/db
      - db:/var/lib/postgresql/data

volumes:
  db:
